server:
  port: 8001

spring:
  application:
    name: RealSight
  # \u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realsight?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-Query: SELECT 1 FROM DUAL #\u9A8C\u8BC1\u8FDE\u63A5SQL\u5FC3\u8DF3
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false

  # redis \u914D\u7F6E
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
      lettuce:
        pool:
          #\u6700\u5927\u8FDE\u63A5\u6570
          max-active: 8
          #\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4
          max-wait: -1
          #\u6700\u5927\u7A7A\u95F2
          max-idle: 8
          #\u6700\u5C0F\u7A7A\u95F2\u65F6\u95F4
          min-idle: 0
        #\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
        timeout: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis-plus\u914D\u7F6E
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted #\u5168\u5C40\u903B\u8F91\u5220\u9664\u7684\u5B9E\u4F53\u5B57\u6BB5\u540D
      logic-delete-value: 1 #\u903B\u8F91\u5DF2\u5220\u9664\u503C\uFF08\u9ED8\u8BA41\uFF09
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C\uFF08\u9ED8\u8BA40\uFF09
  configuration:
    map-underscore-to-camel-case: true #\u9A7C\u5CF0
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u65E5\u5FD7\u914D\u7F6E
  mapper-locations: classpath*:/mapper/**/*.xml

  jwt:
    secret-key: "your-256-bit-secret-key-base64-encoded" # \u5B9E\u9645\u751F\u4EA7\u73AF\u5883\u5EFA\u8BAE\u7528\u73AF\u5883\u53D8\u91CF\u8986\u76D6

  #mybatis-plus.type-aliases-package=com.qm.entity
  # mybatis-plus.global-config.db-config.id-type=auto
  #mybatis-plus.global-config.db-config.table-underline=true
  #logging.level.org.springframework.context=DEBUG
  #logging.level.com.qm:DEBUG
